### ISSUE TITLE
Previous Work/ Future Work

### ISSUE THREAD

**Issue by KPont** [biggiejr/UFO#1]
Can't find much about your previous work except for figure 1 which I think is an old query? Figure 4 and 5 does show old cypher. I would have liked a little bit of explanation of what is going on there, though. Can't see any mention of future work.

Score: 4

**Comment by Athinodoros** [comment]
the previous work is mentioned in blog appropriate detail. The future work relies  on the neo4j team and what they plan to implement in the future. As for now there nothing we could do to completely solve the problems.
