### ISSUE TITLE
Design Constraints and Assumptions

### ISSUE THREAD

**Issue by Sindt** [biggiejr/UFO#2]
You talk a small bit about limitations and possible problems by using neo4j when data is increasing, and you made a good amount of why you originally thought neo4j were the right solution.

However, you didn’t come up with any alternatives to neo4j, which maybe would have been an even better solution, than the ones you figured out.

Score: 7/10

**Comment by biggiejr** [comment]
Thank you for your feedback. 
We focused mainly on fixing problems while still using Neo4j, thats why we went deeper in HA cluster and splitting the queries. We understand your point and agree, but as mentioned before we did not drop the idea of using Neo4j.
