### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by Sindt** [biggiejr/UFO#4]
**Abstract**
You have made a good abstract, which explains the problem clearly. The only thing missing, is a small bit about what your solution to the problem is.

**Our experience with Neo4j**
Good introduction to your experience with Neo4j, and a good explanation of which problems occurred, and what you did to figure out, what the reason was. You write that the problem was due to Neo4j's way of indexing and you have added two figures (no. 1 and 2). However, these figures do not contribute to anything, as the text is very small which makes the image blurred.

Your subsequent explanation of what is done to solve the problem is easy to understand. The same applies to the figures no. 3, 4 and 5.

Your final solution to the problem itself is well described in the text, but again the figure (No. 6) could be better. It doesn’t make your solution it easier to understand and, in our opinion, could be omitted. If the image/figure of the code should be a part of the blog, it would be necessary to better explain what happens line by line.

Overall the overview of the blog is very good.

Score: 8/10

**Comment by biggiejr** [comment]
Thank you for your feedback. We revised and fixed the abstract according to your feedback.
